### PR TITLE
Create j13g.makedown

### PR DESCRIPTION
**Pull request by D3W10**

### CODE REVIEW

**Comment by bigbiff** [comment]
Why is this markdown needed?

**Comment by D3W10** [comment]
To get the TWRP from my Samsung Galaxy J1, to update.


Em 19/12/2017 00:22, "bigbiff" <notifications@github.com> escreveu:

**Comment by bigbiff** [comment]
Did you create a device tree for the device?

**Comment by D3W10** [comment]
No

Em 19/12/2017 00:56, "bigbiff" <notifications@github.com> escreveu:

**Comment by D3W10** [comment]
Why?

Em 19/12/2017 01:13, "bigbiff" <notifications@github.com> escreveu:

Closed #47 <https://github.com/TeamWin/twrpme/pull/47>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TeamWin/twrpme/pull/47#event-1393256015>, or mute the
thread

**Pull request closed without merging**
