### PR TITLE
typo - update lggwatchr

### PR DESCRIPTION
**Pull request by docgalaxyblock**
missing `R` in title
the right device name is `LG G Watch R`

### CODE REVIEW

**Comment by bigbiff** [comment]
Please submit this to our gerrit instance at https://gerrit.twrp.me.

**Comment by docgalaxyblock** [comment]
@bigbiff sry I do not understand how to use this *gerrit*

**Comment by bigbiff** [comment]
Please see the following: https://wiki.lineageos.org/how-to/using-gerrit

Except our URL is gerrit.twrp.me.

**Comment by docgalaxyblock** [comment]
@bigbiff sry that is to complex for me.  I do not get it

**Pull request closed without merging**
