### PR TITLE
Updating configuration to default to https.

### PR DESCRIPTION
**Pull request by chris-barry**

### CODE REVIEW

**Comment by spudowiar** [comment]
Patches come through Gerrit please, not GitHub.

**Comment by bigbiff** [comment]
I don't mind accepting this on gerrit.twrp.me, but fyi, http is rewritten to https on our sites.

**Comment by spudowiar** [comment]
Do you use HSTS? Also, explicit HTTPS is always better.

On 27 Jul 2016 13:03, bigbiff <notifications@github.com> wrote:

I don't mind accepting this on gerrit.twrp.me, but fyi, http is rewritten to https on our sites.

**Comment by chris-barry** [comment]
https by default stops some attacks. I'll be sure to use gerrit in the
future!

**Comment by spudowiar** [comment]
With GitHub, I realise I should turn off 'Quoted text' in the AOSP Email client :/

**Pull request closed without merging**
