### PR TITLE
Update maintainership for j7 2016 :incl new twrp trees

### PR DESCRIPTION
**Pull request by oves786**
https://github.com/TeamWin/android_device_samsung_j7xelte

### CODE REVIEW

**Comment by bigbiff** [comment]
Please push this to the twrpme project at https://gerrit.twrp.me

**Comment by oves786** [comment]
I cant make it i havent used gerrit yet can u help on it..

**Comment by TeamWin-Gerrit** [comment]
Please look at https://forum.xda-developers.com/showthread.php?t=2628545
for a general tutorial. You can submit to ssh://<username>@
gerrit.twrp.me:29418/project HEAD:refs/for/branch_name

We use the github API to authenticate your github username.

**Comment by oves786** [comment]
Oves786@dopebox:~/gerrit/twrpme$ git push
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Counting objects: 4, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 387 bytes | 0 bytes/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3)
remote: Branch refs/heads/master:
remote: You are not allowed to perform this operation.
remote: To push into this reference you need 'Push' rights.
remote: User: oves786
remote: Please read the documentation and contact an administrator
remote: if you feel the configuration is incorrect
remote: Processing changes: refs: 1, done    
To ssh://oves786@gerrit.twrp.me:29418/twrpme.git
 ! [remote rejected] master -> master (prohibited by Gerrit: ref update access denied)
error: failed to push some refs to 'ssh://oves786@gerrit.twrp.me:29418/twrpme.git'

**Pull request closed without merging**
