### PR TITLE
Add links to Googe and Motorola factory images

### PR DESCRIPTION
**Pull request by Walkman100**
https://twrp.me/faq/noos.html
Thought it a bit weird to say "hosts factory images here" and not provide a link.

### CODE REVIEW

**Comment by Walkman100** [comment]
I've had a look at trying to use Gerrit (#4), but I can't find any information on how to clone the repo in order to commit the changes and push... Honestly for such a simple change (that can be Googled too) I'm not putting in the effort.

**Comment by Walkman100** [comment]
Searching for `twrpme` in the Gerrit search brings up a list of commits from the project, then clicking on the name under `project` takes you to https://gerrit.twrp.me/#/q/project:twrpme, which is just a search...

**Comment by Walkman100** [comment]
As per #15#issuecomment-181144438, I've managed to find the url to clone (https://gerrit.twrp.me/twrpme.git), however pushing my commit gives me `remote: Unauthorized` with logging in with my credentials on gerrit.twrp.me

**Comment by bigbiff** [comment]
What does your remote look like?

**Comment by Walkman100** [comment]
```sh
> git config -l
[...]
remote.origin.url=https://gerrit.twrp.me/twrpme.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.master.rebase=true
branch.test.remote=origin
branch.test.merge=refs/heads/test
branch.test.rebase=true
```

**Comment by bigbiff** [comment]
Add your remote as ssh://username@gerrit.twrp.me:29418/twrpme

**Comment by Walkman100** [comment]
First time I've used SSH keys (I have a GPG key), but I got a bit further (I think):
```sh
remote: Resolving deltas: 100% (3/3)
remote: Processing changes: refs: 1, done
remote: ERROR: [609f80c] missing Change-Id in commit message footer
remote:
remote: Hint: To automatically insert Change-Id, install the hook:
remote:   gitdir=$(git rev-parse --git-dir); scp -p -P 29418 Walkman100@gerrit.twrp.me:hooks/commit-msg ${gitdir}/hooks/
remote: And then amend the commit:
remote:   git commit --amend
remote:
To ssh://gerrit.twrp.me:29418/twrpme
 ! [remote rejected] HEAD -> refs/for/test ([609f80c] missing Change-Id in commit message footer)
error: failed to push some refs to 'ssh://Walkman100@gerrit.twrp.me:29418/twrpme'
```

**Comment by Walkman100** [comment]
Woot: https://gerrit.twrp.me/#/c/2481/

**Pull request closed without merging**
