### PR TITLE
Add nx563j markdown

### PR DESCRIPTION
**Pull request by youyim123**

### CODE REVIEW

**Comment by bigbiff** [comment]
This needs to be pushed to the twrp.me project on https://gerrit.twrp.me.

**Comment by youyim123** [comment]
Hi，I ready  upload my project to https://gerrit.twrp.me, but I don’t know how to do it. I read https://gerrit.twrp.me/Documentation/user-upload.html this page, and Testing Connections success, but I don’t know how to upload it. Please tell me, thank you.

**Comment by bigbiff** [comment]
git clone git clone https://gerrit.twrp.me/twrpme
cd twrpme 
git remote add gerrit ssh://username@gerrit.twrp.me:29418/twrp
make updates
git commit -a -m "some message"
git push gerrit HEAD:refs/for/master

**Comment by youyim123** [comment]
please help me.
youyim@youyim:~$ git clone https://gerrit.twrp.me/twrpme
Cloning into 'twrpme'...
remote: Counting objects: 1360, done
remote: Finding sources: 100% (82/82)
remote: Total 4333 (delta 18), reused 4306 (delta 18)
Receiving objects: 100% (4333/4333), 1.04 MiB | 220.00 KiB/s, done.
Resolving deltas: 100% (2252/2252), done.
youyim@youyim:~$ cd twrpme
youyim@youyim:~/twrpme$ git remote add gerrit ssh://youyim123@gerrit.twrp.me:29418/twrp
youyim@youyim:~/twrpme$ git commit -a -m "add nx563j"
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
	_nubia/nubianx563j.markdown

nothing added to commit but untracked files present
youyim@youyim:~/twrpme$ git push gerrit HEAD:refs/for/master
fatal: Project not found: twrp
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
youyim@youyim:~/twrpme$ git add _nubia/nubianx563j.markdown
youyim@youyim:~/twrpme$ git commit -a -m "add nx563j"
[master 2bc1a4c] add nx563j
 1 file changed, 20 insertions(+)
 create mode 100644 _nubia/nubianx563j.markdown
youyim@youyim:~/twrpme$ git push gerrit HEAD:refs/for/master
fatal: Project not found: twrp
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by bigbiff** [comment]
You added twrp as your project remote for gerrit, the project is twrpme.

**Pull request closed without merging**
