### PR TITLE
fix lenok name

### PR DESCRIPTION
**Pull request by JeanPrendnote**
LG G watch = dory
LG G watch R = lenok

https://twrp.me/Devices/

### CODE REVIEW

**Comment by spudowiar** [comment]
Patches come through Gerrit please, not GitHub.

**Comment by h3r03** [comment]
Tolong buatkan file recovery TWRP untuk Hisense Pureshot Plus L695.
Maaf saya tidak bisa bahasa inggris. Saya dari Indonesia.

**Comment by JeanPrendnote** [comment]
not sure if ghost is serious, do you think that i'm going to wast at least 6 hours to learn how to use gerrit lol ? anyways stay with a broken website i don't care.

**Comment by h3r03** [comment]
Can you make up TWRP recovery file for Hisense Pureshot Plus L695.
Sorry, I can not speak English. I am from Indonesia

**Comment by TingyiChen** [comment]
You can push this in gerrit.twrp.me

**Pull request closed without merging**
