### PR TITLE
Add header anchors to common device page sections.

### PR DESCRIPTION
**Pull request by patcon**
Ref: https://github.com/TeamWin/Team-Win-Recovery-Project/issues/378

### CODE REVIEW

**Comment by patcon** [comment]
More generally, the anchor could be a consistent `id='{{ page.path | split:"." | first }}'` using a liquid filter. But then deeplinks would break if you changed filenames behind the scenes, so probably better to be explicit :)

http://stackoverflow.com/questions/13243469/how-can-a-jekyll-page-access-its-filename
https://github.com/Shopify/liquid/wiki/Liquid-for-Designers

**Comment by bigbiff** [comment]
Please use http://gerrit.twrp.me to submit udpates to twrpme.

**Comment by patcon** [comment]
Thanks. Any advice? Can't find docs and the link at the bottom of the readme is broken:

https://github.com/TeamWin/Team-Win-Recovery-Project#readme
http://teamw.in/twrp2-gerrit

**Comment by patcon** [comment]
Ah hey, sorted it out: http://gerrit.twrp.me/Documentation/user-upload.html#_git_push

**Comment by patcon** [comment]
Hm. No error, but nothing in message verifying that I've done it correctly, or where I can look in the web UI to confirm. Any advice is appreciated. Thanks

https://gist.github.com/patcon/cc7c2fa480863af6d64e

**Comment by bigbiff** [comment]
Looks like it made it http://gerrit.twrp.me/#/c/854/

**Pull request closed without merging**
